# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]





require 'easy_money'

path = File.expand_path(__dir__)
Dir.glob("#{path}/tasks/**/*.rake").each { |f| import f }






#Sc: nice example here: https://github.com/norman/friendly_id/blob/81442a69df30a604e63fbbd789ba22464de5c758/Rakefile

desc "Test task"
task :testtask do
  puts "This is a test task"
end






